In [1]:
import sqlite3
import pandas as pd

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
df = pd.read_csv("../data/processed/cleaned_supermarket_sales.csv")

df.head()

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax_5,sales,date,time,payment,cogs,gross_margin_percentage,gross_income,rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [3]:
conn = sqlite3.connect("../data/database/supermarket.db")

print("Database created successfully!")

Database created successfully!

In [4]:
df.to_sql(
    "sales",
    conn,
    if_exists="replace",
    index=False
)

print("Dataset imported into SQLite database successfully!")

Dataset imported into SQLite database successfully!

In [5]:
query = "SELECT * FROM sales LIMIT 5;"

pd.read_sql(query, conn)

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax_5,sales,date,time,payment,cogs,gross_margin_percentage,gross_income,rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [6]:
query = "SELECT * FROM sales LIMIT 5;"
pd.read_sql(query, conn)

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax_5,sales,date,time,payment,cogs,gross_margin_percentage,gross_income,rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [7]:
branches = df[['branch', 'city']].drop_duplicates()

branches.to_sql(
    'branches',
    conn,
    if_exists='replace',
    index=False
)

print("Branches table created!")

Branches table created!

In [8]:
pd.read_sql("SELECT * FROM branches;", conn)

  branch       city
0   Alex     Yangon
1   Giza  Naypyitaw
2  Cairo   Mandalay

In [9]:
products = df[['product_line']].drop_duplicates()

products.to_sql(
    'products',
    conn,
    if_exists='replace',
    index=False
)

print("Products table created!")

Products table created!

In [10]:
pd.read_sql("SELECT * FROM products;", conn)

             product_line
0       Health and beauty
1  Electronic accessories
2      Home and lifestyle
3       Sports and travel
4      Food and beverages
5     Fashion accessories

# Basic SQL Queries

In [11]:
query = """
SELECT * FROM sales;
"""

pd.read_sql(query, conn).head()

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax_5,sales,date,time,payment,cogs,gross_margin_percentage,gross_income,rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [12]:
query = """
SELECT invoice_id, branch, city, sales
FROM sales;
"""

pd.read_sql(query, conn).head()

    invoice_id branch       city     sales
0  750-67-8428   Alex     Yangon  548.9715
1  226-31-3081   Giza  Naypyitaw   80.2200
2  631-41-3108   Alex     Yangon  340.5255
3  123-19-1176   Alex     Yangon  489.0480
4  373-73-7910   Alex     Yangon  634.3785

In [13]:
query = """
SELECT *
FROM sales
WHERE sales > 500;
"""

pd.read_sql(query, conn)

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax_5,sales,date,time,payment,cogs,gross_margin_percentage,gross_income,rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
2,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,2019-03-25,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
3,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2019-02-24,11:38:00 AM,Ewallet,735.60,4.761905,36.7800,8.0
4,829-34-3910,Alex,Yangon,Member,Female,Health and beauty,71.38,10,35.6900,749.4900,2019-03-29,7:21:00 PM,Cash,713.80,4.761905,35.6900,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,2019-03-29,7:12:00 PM,Ewallet,823.40,4.761905,41.1700,4.3
223,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,2019-01-28,3:46:00 PM,Credit card,602.96,4.761905,30.1480,8.4
224,602-16-6955,Cairo,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3000,2019-01-24,6:10:00 PM,Ewallet,766.00,4.761905,38.3000,6.0
225,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2019-03-02,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
226,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2019-02-18,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [14]:
query = """
SELECT *
FROM sales
ORDER BY sales DESC;
"""

pd.read_sql(query, conn).head()

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax_5,sales,date,time,payment,cogs,gross_margin_percentage,gross_income,rating
0,860-79-0874,Giza,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.65,1042.65,2019-02-15,2:53:00 PM,Credit card,993.0,4.761905,49.65,6.6
1,687-47-8271,Alex,Yangon,Normal,Male,Fashion accessories,98.98,10,49.49,1039.29,2019-02-08,4:20:00 PM,Credit card,989.8,4.761905,49.49,8.7
2,283-26-5248,Giza,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.26,1034.46,2019-01-30,8:23:00 PM,Ewallet,985.2,4.761905,49.26,4.5
3,751-41-9720,Giza,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.75,1023.75,2019-01-12,4:18:00 PM,Ewallet,975.0,4.761905,48.75,8.0
4,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.69,1022.49,2019-03-02,5:16:00 PM,Ewallet,973.8,4.761905,48.69,4.4

In [15]:
query = """
SELECT *
FROM sales
LIMIT 10;
"""

pd.read_sql(query, conn)

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax_5,sales,date,time,payment,cogs,gross_margin_percentage,gross_income,rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,2019-03-25,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,Alex,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2019-02-25,2:36:00 PM,Ewallet,413.04,4.761905,20.6520,5.8
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2019-02-24,11:38:00 AM,Ewallet,735.60,4.761905,36.7800,8.0
8,665-32-9167,Alex,Yangon,Member,Female,Health and beauty,36.26,2,3.6260,76.1460,2019-01-10,5:15:00 PM,Credit card,72.52,4.761905,3.6260,7.2
9,692-92-5582,Cairo,Mandalay,Member,Female,Food and beverages,54.84,3,8.2260,172.7460,2019-02-20,1:27:00 PM,Credit card,164.52,4.761905,8.2260,5.9

# Aggregate Functions

In [16]:
query = """
SELECT COUNT(*) AS total_transactions
FROM sales;
"""

pd.read_sql(query, conn)

   total_transactions
0                1000

In [17]:
query = """
SELECT SUM(sales) AS total_sales
FROM sales;
"""

pd.read_sql(query, conn)

   total_sales
0   322966.749

In [18]:
query = """
SELECT AVG(sales) AS average_sales
FROM sales;
"""

pd.read_sql(query, conn)

   average_sales
0     322.966749

In [19]:
query = """
SELECT MAX(sales) AS highest_sale
FROM sales;
"""

pd.read_sql(query, conn)

   highest_sale
0       1042.65

In [20]:
query = """
SELECT MIN(sales) AS lowest_sale
FROM sales;
"""

pd.read_sql(query, conn)

   lowest_sale
0      10.6785

# GROUP BY & HAVING

In [21]:
query = """
SELECT branch, SUM(sales) AS total_sales
FROM sales
GROUP BY branch;
"""

pd.read_sql(query, conn)

  branch  total_sales
0   Alex  106200.3705
1  Cairo  106197.6720
2   Giza  110568.7065

In [22]:
query = """
SELECT city, SUM(sales) AS total_sales
FROM sales
GROUP BY city;
"""

pd.read_sql(query, conn)

        city  total_sales
0   Mandalay  106197.6720
1  Naypyitaw  110568.7065
2     Yangon  106200.3705

In [23]:
query = """
SELECT product_line, AVG(rating) AS average_rating
FROM sales
GROUP BY product_line;
"""

pd.read_sql(query, conn)

             product_line  average_rating
0  Electronic accessories        6.924706
1     Fashion accessories        7.029213
2      Food and beverages        7.113218
3       Health and beauty        7.003289
4      Home and lifestyle        6.837500
5       Sports and travel        6.916265

In [24]:
query = """
SELECT payment, COUNT(*) AS total_transactions
FROM sales
GROUP BY payment;
"""

pd.read_sql(query, conn)

       payment  total_transactions
0         Cash                 344
1  Credit card                 311
2      Ewallet                 345

In [25]:
query = """
SELECT branch, SUM(sales) AS total_sales
FROM sales
GROUP BY branch
HAVING SUM(sales) > 100000;
"""

pd.read_sql(query, conn)

  branch  total_sales
0   Alex  106200.3705
1  Cairo  106197.6720
2   Giza  110568.7065

# JOIN Queries

In [26]:
query = """
SELECT
    s.invoice_id,
    s.branch,
    b.city,
    s.sales
FROM sales s
INNER JOIN branches b
ON s.branch = b.branch;
"""

pd.read_sql(query, conn).head()

    invoice_id branch       city     sales
0  750-67-8428   Alex     Yangon  548.9715
1  226-31-3081   Giza  Naypyitaw   80.2200
2  631-41-3108   Alex     Yangon  340.5255
3  123-19-1176   Alex     Yangon  489.0480
4  373-73-7910   Alex     Yangon  634.3785

In [27]:
query = """
SELECT
    s.invoice_id,
    s.branch,
    b.city,
    s.sales
FROM sales s
LEFT JOIN branches b
ON s.branch = b.branch;
"""

pd.read_sql(query, conn).head()

    invoice_id branch       city     sales
0  750-67-8428   Alex     Yangon  548.9715
1  226-31-3081   Giza  Naypyitaw   80.2200
2  631-41-3108   Alex     Yangon  340.5255
3  123-19-1176   Alex     Yangon  489.0480
4  373-73-7910   Alex     Yangon  634.3785

# Subqueries

A subquery is a query written inside another SQL query. Here, we retrieve all transactions where the sales amount is greater than the average sales value.

In [28]:
query = """
SELECT *
FROM sales
WHERE sales >
(
    SELECT AVG(sales)
    FROM sales
);
"""

pd.read_sql(query, conn)

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax_5,sales,date,time,payment,cogs,gross_margin_percentage,gross_income,rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
2,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
3,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
4,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,2019-03-25,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,2019-03-29,7:12:00 PM,Ewallet,823.40,4.761905,41.1700,4.3
400,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,2019-01-28,3:46:00 PM,Credit card,602.96,4.761905,30.1480,8.4
401,602-16-6955,Cairo,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3000,2019-01-24,6:10:00 PM,Ewallet,766.00,4.761905,38.3000,6.0
402,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2019-03-02,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
403,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2019-02-18,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

# Common Table Expressions (CTEs)

A Common Table Expression (CTE) uses the WITH clause to create a temporary result set that makes complex queries easier to read and maintain.

In [29]:
query = """
WITH branch_sales AS
(
    SELECT
        branch,
        SUM(sales) AS total_sales
    FROM sales
    GROUP BY branch
)

SELECT *
FROM branch_sales;
"""

pd.read_sql(query, conn)

  branch  total_sales
0   Alex  106200.3705
1  Cairo  106197.6720
2   Giza  110568.7065

# Window Functions

Window functions perform calculations across a set of rows related to the current row without grouping the results. This section demonstrates ROW_NUMBER(), RANK(), LAG(), and LEAD().

## ROW_NUMBER()

Assigns a unique sequential number to each transaction based on sales in descending order.

In [31]:
query = """
SELECT
    invoice_id,
    sales,
    ROW_NUMBER() OVER (ORDER BY sales DESC) AS row_num
FROM sales;
"""

pd.read_sql(query, conn).head()

    invoice_id    sales  row_num
0  860-79-0874  1042.65        1
1  687-47-8271  1039.29        2
2  283-26-5248  1034.46        3
3  751-41-9720  1023.75        4
4  303-96-2227  1022.49        5

## RANK()

Ranks transactions according to sales. Transactions with the same sales value receive the same rank.## RANK()

Ranks transactions according to sales. Transactions with the same sales value receive the same rank.

In [32]:
query = """
SELECT
    invoice_id,
    sales,
    RANK() OVER (ORDER BY sales DESC) AS sales_rank
FROM sales;
"""

pd.read_sql(query, conn).head()

    invoice_id    sales  sales_rank
0  860-79-0874  1042.65           1
1  687-47-8271  1039.29           2
2  283-26-5248  1034.46           3
3  751-41-9720  1023.75           4
4  303-96-2227  1022.49           5

## LAG()

Returns the previous transaction's sales value based on ascending sales order.

In [33]:
query = """
SELECT
    invoice_id,
    sales,
    LAG(sales) OVER (ORDER BY sales) AS previous_sale
FROM sales;
"""

pd.read_sql(query, conn).head()

    invoice_id    sales  previous_sale
0  784-21-9238  10.6785            NaN
1  308-39-1707  12.6945        10.6785
2  279-62-1445  13.1670        12.6945
3  192-98-7397  13.4190        13.1670
4  236-86-3015  14.6790        13.4190

## LEAD()

Returns the next transaction's sales value based on ascending sales order.

In [34]:
query = """
SELECT
    invoice_id,
    sales,
    LEAD(sales) OVER (ORDER BY sales) AS next_sale
FROM sales;
"""

pd.read_sql(query, conn).head()

    invoice_id    sales  next_sale
0  784-21-9238  10.6785    12.6945
1  308-39-1707  12.6945    13.1670
2  279-62-1445  13.1670    13.4190
3  192-98-7397  13.4190    14.6790
4  236-86-3015  14.6790    16.1070

# SQL Views

A SQL View is a virtual table created from a SQL query. Views simplify frequently used queries and improve reusability.

In [35]:
query = """
CREATE VIEW IF NOT EXISTS sales_summary AS
SELECT
    branch,
    SUM(sales) AS total_sales
FROM sales
GROUP BY branch;
"""

conn.execute(query)

pd.read_sql("SELECT * FROM sales_summary;", conn)

  branch  total_sales
0   Alex  106200.3705
1  Cairo  106197.6720
2   Giza  110568.7065

# Python & SQL Integration

Python was successfully connected to the SQLite database using the `sqlite3` library.

## Tasks Completed

- Connected to the SQLite database using Python.
- Executed SQL queries directly from Python.
- Loaded SQL query results into Pandas DataFrames using `pandas.read_sql()`.
- Implemented parameterized SQL queries to prevent SQL injection.
- Created a reusable database connection module (`db_utils.py`) for future projects.

This demonstrates seamless integration between Python and SQL for efficient data extraction and analysis.

Retrieve records for the selected branch using a parameterized SQL query.

The dataset contains the branches:
- Alex
- Giza
- Cairo

Parameterized queries prevent SQL injection by safely passing user inputs to the database.

In [44]:
branch_name = "Alex"

query = """
SELECT *
FROM sales
WHERE branch = ?;
"""

df = pd.read_sql(query, conn, params=(branch_name,))

print(df.head())

    invoice_id branch    city customer_type  gender            product_line  \
0  750-67-8428   Alex  Yangon        Member  Female       Health and beauty
1  631-41-3108   Alex  Yangon        Normal  Female      Home and lifestyle
2  123-19-1176   Alex  Yangon        Member  Female       Health and beauty
3  373-73-7910   Alex  Yangon        Member  Female       Sports and travel
4  355-53-5943   Alex  Yangon        Member  Female  Electronic accessories

   unit_price  quantity    tax_5     sales        date         time  \
0       74.69         7  26.1415  548.9715  2019-01-05   1:08:00 PM
1       46.33         7  16.2155  340.5255  2019-03-03   1:23:00 PM
2       58.22         8  23.2880  489.0480  2019-01-27   8:33:00 PM
3       86.31         7  30.2085  634.3785  2019-02-08  10:37:00 AM
4       68.84         6  20.6520  433.6920  2019-02-25   2:36:00 PM

       payment    cogs  gross_margin_percentage  gross_income  rating
0      Ewallet  522.83                 4.761905       26.1415     9.1
1  Credit card  324.31                 4.761905       16.2155     7.4
2      Ewallet  465.76                 4.761905       23.2880     8.4
3      Ewallet  604.17                 4.761905       30.2085     5.3
4      Ewallet  413.04                 4.761905       20.6520     5.8